### ISSUE TITLE
how can i test if a point (circle,image..) is intersected with path or line 

### ISSUE THREAD

**Issue by ElMaghri** [amatiash/svg.intersections.js#1]
hello 
i would test if a point is intersected with a path

**Comment by amatiash** [comment]
Hello!

What you can do, is to split your path into line segments and check if point is on line (iterate over all the lines).
So split first and then check with [.isPointOnLine()](https://github.com/amatiash/svg.intersections.js#module_SVGIntersections..isPointOnLine)
There is an issue with the accuracy you want to have (how long are the segments).

[Another solution](https://stackoverflow.com/questions/20788604/recognize-pointx-y-is-inside-svg-path-or-outside).

**Comment by ElMaghri** [comment]
Hello 
First of all, I want to thank you for your help, but I like to drag a circle all along the path curve (d attr)
this is an exemple with css 
 
https://codepen.io/SaraSoueidan/pen/ef9f0e1242263cf23067b09be894cfa9

**Comment by amatiash** [comment]
Man, look though the web...
[Here](https://codepen.io/ilumin/pen/BLkwJ) is what I found at instant.

Since it's not related to this plugin, I'm closing the issue.
