### ISSUE TITLE
Path inside path

### ISSUE THREAD

**Issue by Hugoer** [amatiash/svg.intersections.js#2]
Is there any way to know if a path is inside other path? i need to know wich path intersect with another path, but if no exists intersection points, it doesn´t work as i expected and i have no idea if it is posible with this plugin. I check other plugins and i didn´t find something similar. Thanks for your amazing work!

**Comment by amatiash** [comment]
This is not related to current plugin - closing the issue.

Answering your question: yes, as an option you can represent a path as an array of dots and check if every single one in inside another path, which is converted to a polygon first. I don't think this is a perfect solution - just an idea, what comes in ming first.
